services:

  is-dev-server:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: ${PROFILE:-dev}
      args:
        WPM_ACCESS_TOKEN: ${PACKAGES_TOKEN}
    image: ${IMAGE_NAME:-msr-solution-dev}:${IMAGE_TAG:-latest}
    container_name: is-dev-server
    volumes:
      - ./server:/server
      - ./license:/license
    environment:
      - EXTERNALIZE_PACKAGES=true
      - HOST_DIR=/server
      - SERVICE_NAME=dev
      - SAG_IS_LICENSE_FILE=/license/licenseKey.xml
    ports:
      - "${IS_MAIN_PORT:-5555}:5555"
      - "${IS_DIAG_PORT:-9999}:9999"

  is-test-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${IMAGE_NAME:-msr-solution}:${IMAGE_TAG:-latest}
      args:
        WPM_ACCESS_TOKEN: ${PACKAGES_TOKEN}
    profiles:
      - test
    image: ${IMAGE_NAME:-msr-solution}:${IMAGE_TAG:-latest}
    restart: always
    container_name: is-test-server
    volumes:
      - ./license:/license
    environment:
      - SAG_IS_LICENSE_FILE=/license/licenseKey.xml
    ports:
      - "${IS_MAIN_PORT:-5555}:5555"
      - "${IS_DIAG_PORT:-9999}:9999"

  is-prod-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${IMAGE_NAME:-msr-solution}:${IMAGE_TAG:-latest}
      args:
        WPM_ACCESS_TOKEN: ${PACKAGES_TOKEN}
    profiles:
      - prod
    image: ${IMAGE_NAME:-msr-solution}:${IMAGE_TAG:-latest}
    restart: always
    container_name: is-prod-server
    volumes:
      - ./license:/license
    environment:
      - SAG_IS_LICENSE_FILE=/license/licenseKey.xml
    ports:
      - "${IS_MAIN_PORT:-5555}:5555"
      - "${IS_DIAG_PORT:-9999}:9999"