services:

  is-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    environment:
      - EXTERNALIZE_PACKAGES=${EXTERNALIZE_PACKAGES:-true}
      - HOST_DIR=/server
      - SERVICE_NAME=${ENVIRONMENT}
      - SAG_IS_LICENSE_FILE=/license/${SAG_IS_LICENSE_FILE:-licenseKey.xml}
    image: ${IMAGE_NAME:-msr-solution-dev}:${IMAGE_TAG:-latest}
    volumes:
      - ./license:/license
      - ./server:/server
    ports:
      - "${IS_MAIN_PORT:-5555}:5555"
      - "${IS_DIAG_PORT:-9999}:9999"

    
